// <auto-generated />
using AtulaDotNetTest.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AtulaDotNetTest.Migrations.ProdCatDataSeed
{
    [DbContext(typeof(WebAppContext))]
    partial class WebAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AtulaDotNetTest.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "table"
                        },
                        new
                        {
                            Id = 2,
                            Name = "chair"
                        },
                        new
                        {
                            Id = 3,
                            Name = "sofa"
                        });
                });

            modelBuilder.Entity("AtulaDotNetTest.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Sku")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "lorem table",
                            Sku = 2
                        },
                        new
                        {
                            Id = 2,
                            Name = "ipsum table",
                            Sku = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "dolor table",
                            Sku = 4
                        },
                        new
                        {
                            Id = 4,
                            Name = "sit chair",
                            Sku = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "amet chair",
                            Sku = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "consectetur chair",
                            Sku = 5
                        },
                        new
                        {
                            Id = 7,
                            Name = "adipiscing sofa",
                            Sku = 9
                        },
                        new
                        {
                            Id = 8,
                            Name = "elit sofa",
                            Sku = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "mauris sofa",
                            Sku = 3
                        });
                });

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("CategoryProduct");

                    b.HasData(
                        new
                        {
                            CategoriesId = 1,
                            ProductsId = 1
                        },
                        new
                        {
                            CategoriesId = 1,
                            ProductsId = 2
                        },
                        new
                        {
                            CategoriesId = 1,
                            ProductsId = 3
                        },
                        new
                        {
                            CategoriesId = 2,
                            ProductsId = 4
                        },
                        new
                        {
                            CategoriesId = 2,
                            ProductsId = 5
                        },
                        new
                        {
                            CategoriesId = 2,
                            ProductsId = 6
                        },
                        new
                        {
                            CategoriesId = 3,
                            ProductsId = 7
                        },
                        new
                        {
                            CategoriesId = 3,
                            ProductsId = 8
                        },
                        new
                        {
                            CategoriesId = 3,
                            ProductsId = 9
                        });
                });

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.HasOne("AtulaDotNetTest.Model.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtulaDotNetTest.Model.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
